//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.02 at 01:42:08 PM YEKT 
//


package project.java.trip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TripStr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TripStr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country_departure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="place_departure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country_destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="place_destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date_out" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="target_mission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kontragent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osnovanie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osnovanie_live" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="doc_osnovanie_live" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticket_osnovanie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="doc_ticket_osnovanie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type_transport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticket_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TripStr", propOrder = {
    "countryDeparture",
    "placeDeparture",
    "countryDestination",
    "placeDestination",
    "dateOut",
    "targetMission",
    "kontragent",
    "osnovanie",
    "osnovanieLive",
    "docOsnovanieLive",
    "ticketOsnovanie",
    "docTicketOsnovanie",
    "typeTransport",
    "ticketClass"
})
public class TripStr {

    @XmlElement(name = "country_departure", required = true)
    protected String countryDeparture;
    @XmlElement(name = "place_departure", required = true)
    protected String placeDeparture;
    @XmlElement(name = "country_destination", required = true)
    protected String countryDestination;
    @XmlElement(name = "place_destination", required = true)
    protected String placeDestination;
    @XmlElement(name = "date_out", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOut;
    @XmlElement(name = "target_mission", required = true)
    protected String targetMission;
    @XmlElement(required = true)
    protected String kontragent;
    @XmlElement(required = true)
    protected String osnovanie;
    @XmlElement(name = "osnovanie_live", required = true)
    protected String osnovanieLive;
    @XmlElement(name = "doc_osnovanie_live", required = true)
    protected String docOsnovanieLive;
    @XmlElement(name = "ticket_osnovanie", required = true)
    protected String ticketOsnovanie;
    @XmlElement(name = "doc_ticket_osnovanie", required = true)
    protected String docTicketOsnovanie;
    @XmlElement(name = "type_transport", required = true)
    protected String typeTransport;
    @XmlElement(name = "ticket_class", required = true)
    protected String ticketClass;

    /**
     * Gets the value of the countryDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryDeparture() {
        return countryDeparture;
    }

    /**
     * Sets the value of the countryDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryDeparture(String value) {
        this.countryDeparture = value;
    }

    /**
     * Gets the value of the placeDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceDeparture() {
        return placeDeparture;
    }

    /**
     * Sets the value of the placeDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceDeparture(String value) {
        this.placeDeparture = value;
    }

    /**
     * Gets the value of the countryDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryDestination() {
        return countryDestination;
    }

    /**
     * Sets the value of the countryDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryDestination(String value) {
        this.countryDestination = value;
    }

    /**
     * Gets the value of the placeDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceDestination() {
        return placeDestination;
    }

    /**
     * Sets the value of the placeDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceDestination(String value) {
        this.placeDestination = value;
    }

    /**
     * Gets the value of the dateOut property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOut() {
        return dateOut;
    }

    /**
     * Sets the value of the dateOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOut(XMLGregorianCalendar value) {
        this.dateOut = value;
    }

    /**
     * Gets the value of the targetMission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMission() {
        return targetMission;
    }

    /**
     * Sets the value of the targetMission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMission(String value) {
        this.targetMission = value;
    }

    /**
     * Gets the value of the kontragent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontragent() {
        return kontragent;
    }

    /**
     * Sets the value of the kontragent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontragent(String value) {
        this.kontragent = value;
    }

    /**
     * Gets the value of the osnovanie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsnovanie() {
        return osnovanie;
    }

    /**
     * Sets the value of the osnovanie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsnovanie(String value) {
        this.osnovanie = value;
    }

    /**
     * Gets the value of the osnovanieLive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsnovanieLive() {
        return osnovanieLive;
    }

    /**
     * Sets the value of the osnovanieLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsnovanieLive(String value) {
        this.osnovanieLive = value;
    }

    /**
     * Gets the value of the docOsnovanieLive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocOsnovanieLive() {
        return docOsnovanieLive;
    }

    /**
     * Sets the value of the docOsnovanieLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocOsnovanieLive(String value) {
        this.docOsnovanieLive = value;
    }

    /**
     * Gets the value of the ticketOsnovanie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketOsnovanie() {
        return ticketOsnovanie;
    }

    /**
     * Sets the value of the ticketOsnovanie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketOsnovanie(String value) {
        this.ticketOsnovanie = value;
    }

    /**
     * Gets the value of the docTicketOsnovanie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocTicketOsnovanie() {
        return docTicketOsnovanie;
    }

    /**
     * Sets the value of the docTicketOsnovanie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocTicketOsnovanie(String value) {
        this.docTicketOsnovanie = value;
    }

    /**
     * Gets the value of the typeTransport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeTransport() {
        return typeTransport;
    }

    /**
     * Sets the value of the typeTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeTransport(String value) {
        this.typeTransport = value;
    }

    /**
     * Gets the value of the ticketClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketClass() {
        return ticketClass;
    }

    /**
     * Sets the value of the ticketClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketClass(String value) {
        this.ticketClass = value;
    }

}
