//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.16 at 06:45:16 PM YEKT 
//


package project.java.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TripRec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TripRec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestExternalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="req_auto_card" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="req_pid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="req_fio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mis_auto_card" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mis_pid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mis_fio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mis_code_appoint" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mis_name_appoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mis_struct_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mis_RHR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Code_mission" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateDismissal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="beg_date_miss" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="end_data_miss" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="text_miss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="beg_date_event" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="end_data_event" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="summ_dd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="card_avanse" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="summa_ticket_avanse" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="class_ticket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summa_avanse_living" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="international" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="str" type="{}TripStr" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TripRec", propOrder = {
    "requestExternalId",
    "status",
    "reqAutoCard",
    "reqPid",
    "reqFio",
    "misAutoCard",
    "misPid",
    "misFio",
    "misCodeAppoint",
    "misNameAppoint",
    "misStructCode",
    "misRHR",
    "codeMission",
    "dateDismissal",
    "begDateMiss",
    "endDataMiss",
    "textMiss",
    "begDateEvent",
    "endDataEvent",
    "summDd",
    "cardAvanse",
    "summaTicketAvanse",
    "classTicket",
    "summaAvanseLiving",
    "international",
    "str"
})
public class TripRec {

    @XmlElement(required = true)
    protected String requestExternalId;
    protected int status;
    @XmlElement(name = "req_auto_card")
    protected int reqAutoCard;
    @XmlElement(name = "req_pid")
    protected int reqPid;
    @XmlElement(name = "req_fio", required = true)
    protected String reqFio;
    @XmlElement(name = "mis_auto_card")
    protected int misAutoCard;
    @XmlElement(name = "mis_pid")
    protected int misPid;
    @XmlElement(name = "mis_fio", required = true)
    protected String misFio;
    @XmlElement(name = "mis_code_appoint")
    protected int misCodeAppoint;
    @XmlElement(name = "mis_name_appoint", required = true)
    protected String misNameAppoint;
    @XmlElement(name = "mis_struct_code")
    protected int misStructCode;
    @XmlElement(name = "mis_RHR", required = true)
    protected String misRHR;
    @XmlElement(name = "Code_mission")
    protected int codeMission;
    protected int dateDismissal;
    @XmlElement(name = "beg_date_miss", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar begDateMiss;
    @XmlElement(name = "end_data_miss", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDataMiss;
    @XmlElement(name = "text_miss", required = true)
    protected String textMiss;
    @XmlElement(name = "beg_date_event", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar begDateEvent;
    @XmlElement(name = "end_data_event", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDataEvent;
    @XmlElement(name = "summ_dd")
    protected double summDd;
    @XmlElement(name = "card_avanse")
    protected int cardAvanse;
    @XmlElement(name = "summa_ticket_avanse")
    protected double summaTicketAvanse;
    @XmlElement(name = "class_ticket", required = true)
    protected String classTicket;
    @XmlElement(name = "summa_avanse_living")
    protected double summaAvanseLiving;
    protected int international;
    protected List<TripStr> str;

    /**
     * Gets the value of the requestExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestExternalId() {
        return requestExternalId;
    }

    /**
     * Sets the value of the requestExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestExternalId(String value) {
        this.requestExternalId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the reqAutoCard property.
     * 
     */
    public int getReqAutoCard() {
        return reqAutoCard;
    }

    /**
     * Sets the value of the reqAutoCard property.
     * 
     */
    public void setReqAutoCard(int value) {
        this.reqAutoCard = value;
    }

    /**
     * Gets the value of the reqPid property.
     * 
     */
    public int getReqPid() {
        return reqPid;
    }

    /**
     * Sets the value of the reqPid property.
     * 
     */
    public void setReqPid(int value) {
        this.reqPid = value;
    }

    /**
     * Gets the value of the reqFio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqFio() {
        return reqFio;
    }

    /**
     * Sets the value of the reqFio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqFio(String value) {
        this.reqFio = value;
    }

    /**
     * Gets the value of the misAutoCard property.
     * 
     */
    public int getMisAutoCard() {
        return misAutoCard;
    }

    /**
     * Sets the value of the misAutoCard property.
     * 
     */
    public void setMisAutoCard(int value) {
        this.misAutoCard = value;
    }

    /**
     * Gets the value of the misPid property.
     * 
     */
    public int getMisPid() {
        return misPid;
    }

    /**
     * Sets the value of the misPid property.
     * 
     */
    public void setMisPid(int value) {
        this.misPid = value;
    }

    /**
     * Gets the value of the misFio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisFio() {
        return misFio;
    }

    /**
     * Sets the value of the misFio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisFio(String value) {
        this.misFio = value;
    }

    /**
     * Gets the value of the misCodeAppoint property.
     * 
     */
    public int getMisCodeAppoint() {
        return misCodeAppoint;
    }

    /**
     * Sets the value of the misCodeAppoint property.
     * 
     */
    public void setMisCodeAppoint(int value) {
        this.misCodeAppoint = value;
    }

    /**
     * Gets the value of the misNameAppoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisNameAppoint() {
        return misNameAppoint;
    }

    /**
     * Sets the value of the misNameAppoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisNameAppoint(String value) {
        this.misNameAppoint = value;
    }

    /**
     * Gets the value of the misStructCode property.
     * 
     */
    public int getMisStructCode() {
        return misStructCode;
    }

    /**
     * Sets the value of the misStructCode property.
     * 
     */
    public void setMisStructCode(int value) {
        this.misStructCode = value;
    }

    /**
     * Gets the value of the misRHR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMisRHR() {
        return misRHR;
    }

    /**
     * Sets the value of the misRHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMisRHR(String value) {
        this.misRHR = value;
    }

    /**
     * Gets the value of the codeMission property.
     * 
     */
    public int getCodeMission() {
        return codeMission;
    }

    /**
     * Sets the value of the codeMission property.
     * 
     */
    public void setCodeMission(int value) {
        this.codeMission = value;
    }

    /**
     * Gets the value of the dateDismissal property.
     * 
     */
    public int getDateDismissal() {
        return dateDismissal;
    }

    /**
     * Sets the value of the dateDismissal property.
     * 
     */
    public void setDateDismissal(int value) {
        this.dateDismissal = value;
    }

    /**
     * Gets the value of the begDateMiss property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBegDateMiss() {
        return begDateMiss;
    }

    /**
     * Sets the value of the begDateMiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBegDateMiss(XMLGregorianCalendar value) {
        this.begDateMiss = value;
    }

    /**
     * Gets the value of the endDataMiss property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDataMiss() {
        return endDataMiss;
    }

    /**
     * Sets the value of the endDataMiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDataMiss(XMLGregorianCalendar value) {
        this.endDataMiss = value;
    }

    /**
     * Gets the value of the textMiss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextMiss() {
        return textMiss;
    }

    /**
     * Sets the value of the textMiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextMiss(String value) {
        this.textMiss = value;
    }

    /**
     * Gets the value of the begDateEvent property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBegDateEvent() {
        return begDateEvent;
    }

    /**
     * Sets the value of the begDateEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBegDateEvent(XMLGregorianCalendar value) {
        this.begDateEvent = value;
    }

    /**
     * Gets the value of the endDataEvent property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDataEvent() {
        return endDataEvent;
    }

    /**
     * Sets the value of the endDataEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDataEvent(XMLGregorianCalendar value) {
        this.endDataEvent = value;
    }

    /**
     * Gets the value of the summDd property.
     * 
     */
    public double getSummDd() {
        return summDd;
    }

    /**
     * Sets the value of the summDd property.
     * 
     */
    public void setSummDd(double value) {
        this.summDd = value;
    }

    /**
     * Gets the value of the cardAvanse property.
     * 
     */
    public int getCardAvanse() {
        return cardAvanse;
    }

    /**
     * Sets the value of the cardAvanse property.
     * 
     */
    public void setCardAvanse(int value) {
        this.cardAvanse = value;
    }

    /**
     * Gets the value of the summaTicketAvanse property.
     * 
     */
    public double getSummaTicketAvanse() {
        return summaTicketAvanse;
    }

    /**
     * Sets the value of the summaTicketAvanse property.
     * 
     */
    public void setSummaTicketAvanse(double value) {
        this.summaTicketAvanse = value;
    }

    /**
     * Gets the value of the classTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassTicket() {
        return classTicket;
    }

    /**
     * Sets the value of the classTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassTicket(String value) {
        this.classTicket = value;
    }

    /**
     * Gets the value of the summaAvanseLiving property.
     * 
     */
    public double getSummaAvanseLiving() {
        return summaAvanseLiving;
    }

    /**
     * Sets the value of the summaAvanseLiving property.
     * 
     */
    public void setSummaAvanseLiving(double value) {
        this.summaAvanseLiving = value;
    }

    /**
     * Gets the value of the international property.
     * 
     */
    public int getInternational() {
        return international;
    }

    /**
     * Sets the value of the international property.
     * 
     */
    public void setInternational(int value) {
        this.international = value;
    }

    /**
     * Gets the value of the str property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the str property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TripStr }
     * 
     * 
     */
    public List<TripStr> getStr() {
        if (str == null) {
            str = new ArrayList<TripStr>();
        }
        return this.str;
    }

}
