package project.java;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public static void main(String[] args) throws SQLException {
        String sql = "insert into info (data) values ('autogenerated'),('x');";
        try (Connection connection = ConnectionManager.getConnection();
             var statement = connection.createStatement()) {
            int count = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            System.out.println("count=" + count);
            statement.getGeneratedKeys().next();
            int id = statement.getGeneratedKeys().getInt("id");
            System.out.println("id=" + id);
        }
    }
}
