package project.java;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) throws SQLException {
        String sql = String.format("insert into info (data) values ('%s'),('%s');", "autogenerated", "x");
        List<Integer> ids = new ArrayList<>();
        try (Connection connection = ConnectionManager.getConnection();
             var statement = connection.createStatement()) {
            int count = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            System.out.println("count=" + count);
            while (statement.getGeneratedKeys().next()) {
                Integer id = statement.getGeneratedKeys().getObject("id", Integer.class);
                ids.add(id);
            }
            System.out.println("ids=" + ids);
        }
    }
}
